name: Build and Push Docker Images



on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web image
        uses: docker/build-push-action@v4
        with:
          context: ./web
          push: true
          no-cache: true
          tags: ghcr.io/eduardfabi/assignment3_public-web:latest
      
      - name: Build and push redis image
        uses: docker/build-push-action@v4
        with:
          context: ./redis
          push: true
          no-cache: true
          tags: ghcr.io/eduardfabi/assignment3_public-redis:latest
